export const barangayList = [
  { "id": 1, "barangay": "Adia", "user_id": 1001 },
  { "id": 2, "barangay": "Bagong Pook", "user_id": 1002 },
  { "id": 3, "barangay": "Bagumbayan", "user_id": 1003 },
  { "id": 4, "barangay": "Bubukal", "user_id": 1004 },
  { "id": 5, "barangay": "Cabooan", "user_id": 1005 },
  { "id": 6, "barangay": "Calangay", "user_id": 1006 },
  { "id": 7, "barangay": "Cambuja", "user_id": 1007 },
  { "id": 8, "barangay": "Coralan", "user_id": 1008 },
  { "id": 9, "barangay": "Cueva", "user_id": 1009 },
  { "id": 10, "barangay": "Inayapan", "user_id": 1010 },
  { "id": 11, "barangay": "Jose Laurel, Sr.", "user_id": 1011 },
  { "id": 12, "barangay": "Kayhakat", "user_id": 1012 },
  { "id": 13, "barangay": "Macasipac", "user_id": 1013 },
  { "id": 14, "barangay": "Masinao", "user_id": 1014 },
  { "id": 15, "barangay": "Mataling-Ting", "user_id": 1015 },
  { "id": 16, "barangay": "Pao-o", "user_id": 1016 },
  { "id": 17, "barangay": "Parang Ng Buho", "user_id": 1017 },
  { "id": 18, "barangay": "Barangay I (Poblacion)", "user_id": 1018 },
  { "id": 19, "barangay": "Barangay II (Poblacion)", "user_id": 1019 },
  { "id": 20, "barangay": "Barangay III (Poblacion)", "user_id": 1020 },
  { "id": 21, "barangay": "Barangay IV (Poblacion)", "user_id": 1021 },
  { "id": 22, "barangay": "Jose Rizal", "user_id": 1022 },
  { "id": 23, "barangay": "Santiago", "user_id": 1023 },
  { "id": 24, "barangay": "Talangka", "user_id": 1024 },
  { "id": 25, "barangay": "Tungkod", "user_id": 1025 }
]
